language: node_js

node_js:
  - 10.15.0
  
cache: yarn

before_install:
  - yarn
  
script:
  - yarn run build:prod
  
after_script:
  - chmod 600 ./key
  - rsync -r ./dist/* -e "ssh -o StrictHostKeyChecking=no -i ./key -p ${XDPORT}" ${XDUSER}@${XDHOST}:${XDPATH}
