language: node_js

node_js:
  - 10.15.0
  
cache: yarn

before_install:
  - yarn
  - openssl aes-256-cbc -K $encrypted_b797f2fad051_key -iv $encrypted_b797f2fad051_iv -in privatekey.enc -out privatekey -d
  
script:
  - yarn run build:prod
  
after_script:
  - chmod 600 ./privatekey
  - rsync -r /home/travis/build/xiaodit/think-element/dist/* -e "ssh -o StrictHostKeyChecking=no -p ${XDPORT} -i ./privatekey" ${XDUSER}@${XDHOST}:~/lnmp/workspace/ant/ele
